{"uuid": "bcedf055-1b64-4ee0-8a65-6cd4fc756555", "children": ["dd3350f4-564d-49bd-af1c-ae9c84204cdc", "1b639f6f-36c8-4ac2-891a-c146376f0132", "92451e1a-e97d-41c4-82d7-46e9f292df89", "53d30942-7730-478b-a6d7-ce69907c44ac", "15b9ed1c-50fd-4860-9a38-0bf20d11fbed", "86bab928-3882-4040-babd-5e9da86f3dae", "435e03fb-d2f7-4129-bbfd-6a9d00aeb898"], "befores": [{"name": "xunit_setup_class_fixture_TestUser", "status": "passed", "start": 1627893554257, "stop": 1627893554257}], "afters": [{"name": "xunit_setup_class_fixture_TestUser::0", "status": "broken", "statusDetails": {"message": "pymysql.err.ProgrammingError: (1064, \"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1\")\n", "trace": "  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\_pytest\\python.py\", line 815, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"F:\\shj\\YT_interface2\\testcase\\test_set.py\", line 293, in teardown_class\n    self.sql_exec.update(self.sql['user']['clear_relate'].format(userId_tuple))\n  File \"F:\\shj\\YT_interface2\\common\\execSql.py\", line 63, in update\n    self.cur.execute(sql)\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\pymysql\\cursors.py\", line 148, in execute\n    result = self._query(query)\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\pymysql\\cursors.py\", line 310, in _query\n    conn.query(q)\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 548, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 775, in _read_query_result\n    result.read()\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 1156, in read\n    first_packet = self.connection._read_packet()\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 725, in _read_packet\n    packet.raise_for_error()\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\pymysql\\protocol.py\", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File \"f:\\shj\\yt_interface2\\venv\\lib\\site-packages\\pymysql\\err.py\", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\n"}, "start": 1627893554260, "stop": 1627893554527}], "start": 1627893554257, "stop": 1627893554527}