{"status": "broken", "uuid": "d3a79813-4fc0-4ec2-8e6b-9d9f7c026975", "labels": [{"name": "story", "value": "用户信息查询接口"}, {"name": "feature", "value": "用户管理"}, {"name": "tag", "value": "@pytest.mark.usefixtures('userId')"}, {"name": "suite", "value": "test_set"}, {"name": "subSuite", "value": "TestUser"}, {"name": "parentSuite", "value": "testcase"}, {"name": "host", "value": "DESKTOP-M0PGOTF"}, {"name": "thread", "value": "4156-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "testcase.test_set"}], "stop": 1628559347524, "testCaseId": "b625e37d040d10c4ae577bb256d4c6dc", "historyId": "3ce6a0761b83ef8633eff7623791a978", "start": 1628559347524, "fullName": "testcase.test_set.TestUser#test_user_list", "statusDetails": {"message": "TypeError: 'NoneType' object has no attribute '__getitem__'", "trace": "@pytest.fixture(scope='session')\n    def userId():\n>       userId = Login().yt_login('易通')['data']['userId']\nE       TypeError: 'NoneType' object has no attribute '__getitem__'\n\ntestcase\\conftest.py:23: TypeError"}, "name": "test_user_list"}