{"status": "broken", "name": "用例标题：正确用户名，错误密码", "parameters": [{"name": "expected", "value": "{'status': 200, 'message': 'countryName:...edValue: null'}"}, {"name": "test_input", "value": "{'mobile': '18509251761', 'name': 'sue1'}"}, {"name": "title", "value": "'正确用户名，错误密码'"}], "labels": [{"name": "feature", "value": "地址管理"}, {"name": "story", "value": "新增地址接口"}, {"name": "tag", "value": "@pytest.mark.usefixtures('userId')"}, {"name": "suite", "value": "test_set"}, {"name": "subSuite", "value": "TestAddress"}, {"name": "parentSuite", "value": "testcase"}, {"name": "host", "value": "DESKTOP-M0PGOTF"}, {"name": "thread", "value": "13804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "testcase.test_set"}], "stop": 1629252153644, "testCaseId": "bf17445e686dbbb6b15bcce899bdd76d", "historyId": "11aaf27a79185dc927467199c24a6d19", "start": 1629252153644, "fullName": "testcase.test_set.TestAddress#test_addr_add", "statusDetails": {"message": "TypeError: 'NoneType' object has no attribute '__getitem__'", "trace": "@pytest.fixture(scope='session')\n    def userId():\n>       userId = Login().yt_login('易通')['data']['userId']\nE       TypeError: 'NoneType' object has no attribute '__getitem__'\n\ntestcase\\conftest.py:23: TypeError"}, "uuid": "b3c43e51-7aba-476b-afd6-025ecc209a32"}