{"status": "broken", "name": "用例标题：用户名填写重复，提示用户名已存在", "parameters": [{"name": "expected", "value": "{'status': 500, 'message': u'\\u7528\\u6237\\u540d\\u5df2\\u5b58\\u5728\\uff01'}"}, {"name": "test_input", "value": "{'username': 'SUE_ZK04_A02', 'password': 'UXExMjM0NTY=', 'cnName': u'\\u7528\\u62372', 'confirm': 'Qq123456', 'roleId': 138, 'phoneNumber': '13200000002'}"}, {"name": "title", "value": "'用户名填写重复，提示用户名已存在'"}], "labels": [{"name": "story", "value": "新增用户信息接口"}, {"name": "feature", "value": "用户管理"}, {"name": "tag", "value": "@pytest.mark.usefixtures('userId')"}, {"name": "suite", "value": "test_set"}, {"name": "subSuite", "value": "TestUser"}, {"name": "parentSuite", "value": "testcase"}, {"name": "host", "value": "DESKTOP-M0PGOTF"}, {"name": "thread", "value": "13804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "testcase.test_set"}], "stop": 1629252153719, "testCaseId": "927452938cd34b471a14569bf7d98541", "historyId": "c97964472474c4eb80381a2f0eab8f58", "start": 1629252153719, "fullName": "testcase.test_set.TestUser#test_user_add", "statusDetails": {"message": "TypeError: 'NoneType' object has no attribute '__getitem__'", "trace": "@pytest.fixture(scope='session')\n    def userId():\n>       userId = Login().yt_login('易通')['data']['userId']\nE       TypeError: 'NoneType' object has no attribute '__getitem__'\n\ntestcase\\conftest.py:23: TypeError"}, "uuid": "6e80b48f-92c4-41d4-ba2e-0dd83bb6b7ac"}