{"status": "broken", "uuid": "5168319c-dabb-4bc0-85a0-b7c414d93eed", "labels": [{"name": "story", "value": "修改个人信息接口"}, {"name": "feature", "value": "个人信息"}, {"name": "tag", "value": "@pytest.mark.usefixtures('userId')"}, {"name": "suite", "value": "test_set"}, {"name": "subSuite", "value": "TestPerson"}, {"name": "parentSuite", "value": "testcase"}, {"name": "host", "value": "DESKTOP-M0PGOTF"}, {"name": "thread", "value": "13804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "testcase.test_set"}], "stop": 1629252153752, "testCaseId": "6eb60da9ec56ca0095c9b5a122b9bc66", "historyId": "c142ccd1e0b0810ef831e412fe1c7a1d", "start": 1629252153752, "fullName": "testcase.test_set.TestPerson#test_person_update", "statusDetails": {"message": "TypeError: 'NoneType' object has no attribute '__getitem__'", "trace": "@pytest.fixture(scope='session')\n    def userId():\n>       userId = Login().yt_login('易通')['data']['userId']\nE       TypeError: 'NoneType' object has no attribute '__getitem__'\n\ntestcase\\conftest.py:23: TypeError"}, "name": "test_person_update"}