{"status": "broken", "name": "用例标题：正确的用户信息（填写必填字段）", "parameters": [{"name": "expected", "value": "{'status': 200, 'message': 'OK'}"}, {"name": "test_input", "value": "{'username': 'SUE_ZK04_A02', 'password': 'UXExMjM0NTY=', 'cnName': u'\\u7528\\u62372', 'confirm': 'Qq123456', 'roleId': 138, 'phoneNumber': '13200000002'}"}, {"name": "title", "value": "'正确的用户信息（填写必填字段）'"}], "labels": [{"name": "story", "value": "新增用户信息接口"}, {"name": "feature", "value": "用户管理"}, {"name": "tag", "value": "@pytest.mark.usefixtures('userId')"}, {"name": "suite", "value": "test_set"}, {"name": "subSuite", "value": "TestUser"}, {"name": "parentSuite", "value": "testcase"}, {"name": "host", "value": "DESKTOP-M0PGOTF"}, {"name": "thread", "value": "13804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "testcase.test_set"}], "stop": 1629252153714, "testCaseId": "927452938cd34b471a14569bf7d98541", "historyId": "13a5fa8338337b75065962a87d1f335d", "start": 1629252153714, "fullName": "testcase.test_set.TestUser#test_user_add", "statusDetails": {"message": "TypeError: 'NoneType' object has no attribute '__getitem__'", "trace": "@pytest.fixture(scope='session')\n    def userId():\n>       userId = Login().yt_login('易通')['data']['userId']\nE       TypeError: 'NoneType' object has no attribute '__getitem__'\n\ntestcase\\conftest.py:23: TypeError"}, "uuid": "6cfd970d-7e04-4fa4-bc0f-515da2aa23b5"}